services:
  frontend:
    build:
      context: ./task-manager-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./task-manager-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
